{{- if .Values.secrets.db.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.db.name }}
type: Opaque
stringData:
  username: {{ .Values.secrets.db.username | quote }}
  password: {{ .Values.secrets.db.password | quote }}
{{- end }}
