apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orders.fullname" . }}-sa
{{- if .Values.image.pullSecrets }}
imagePullSecrets:
{{- range .Values.image.pullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}